apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/instance: {{ .Values.frontend.name }}
    app.kubernetes.io/name: {{ .Values.frontend.name }}   
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: shop.projectotus.publicvm.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              name: http
        path: /
        pathType: ImplementationSpecific