apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterissuer }}
  labels:
    app.kubernetes.io/instance: {{ .Values.frontend.name }}
    app.kubernetes.io/name: {{ .Values.frontend.name }}   
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.externalname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.ingress.externalname }}
    secretName: frontend-tls