apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack-charts
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki-stack
    repoURL: https://github.com/AlexClev/otusproject/tree/main/Monitoring/helm-charts/loki-stack
    targetRevision: 2.5.0
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true

  