name: install web application

on:
  workflow_dispatch
#  push:
    # при создании pull request на main
#    branches: [ main ]

jobs:
  install_app:
    runs-on: ubuntu-latest
 
    steps:
      - name: install argocd cli
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd

      - name: login argocd 
        run: |
          argocd login ${{ vars.ARGO_URI }} --username admin --password ${{ secrets.AGRO_PASS }} --insecure
       
      - name: install web app
        run: |
          argocd app create shop --repo ${{ vars.GIT_ADDRESS }} --path helm-charts/demo  --dest-namespace apps --dest-server https://kubernetes.default.svc --sync-policy auto --sync-option CreateNamespace=true  
          
          








          
