name: settings argo

on:
  workflow_dispatch
#  push:
    # при создании pull request на main
#    branches: [ main ]

jobs:
  install_argo:
    runs-on: ubuntu-latest
    env:
      ya_cluster_name: ${{ vars.YA_CLUSTER_NAME }}
#      ya_account: ${{ secrets.YA_ACCOUNT }}
      ya_cloud_id: ${{ vars.YA_CLUSTER_ID }}
      ya_folder_id: ${{ vars.YA_FOLDER_ID }}
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  install yandex cli
        uses: nightstory/setup-yc@v1
        with:
          enable-cache: true

      - run: 'echo "$YA_KEY" > key.json'
        shell: bash
        env:
          YA_KEY: ${{ secrets.YC_SA }}
   
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        id: install

      - name: set yandex env
        run: |
          yc config set cloud-id ${{ env.ya_cloud_id }}
          yc config set folder-id ${{ env.ya_folder_id }}
          yc config set service-account-key key.json
          yc managed-kubernetes cluster get-credentials ${{ env.ya_cluster_name }} --external

 #     - name: create keys for argo
#        run: 'echo "${{ secrets.ARGO_CRT }}" > tls.crt && echo "${{ secrets.ARGO_KEY }}" > tls.key'
 #       shell: bash
  
 #     - name: install argocd
 #       run: |
 #         kubectl apply -n argocd  -f https://raw.githubusercontent.com/AlexClev/otusproject/main/argocd/argocd-deploy.yaml

#     - name: install ingress
 #       run: |
#          kubectl apply -f https://raw.githubusercontent.com/AlexClev/otusproject/main/ingress/ingress-deploy.yaml 


      - name: install argocd cli
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd

      - name: get pass argocd 
        id: argopass
        run: |
          kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d | xargs -I OLD_PASS echo "oldpass=OLD_PASS" >> $GITHUB_OUTPUT 
          echo $GITHUB_OUTPUT 
                  
      - name: change pass argocd 
        run: |
          argocd login ${{ vars.ARGO_URI }} --username admin --password ${{ steps.argopass.outputs.oldpass }} --insecure
          argocd account update-password --account admin --current-password ${{ steps.argopass.outputs.oldpass }} --new-password ${{ secrets.AGRO_PASS }}

      - name: add git repository
        run: |
          argocd repo add ${{ vars.GIT_ADDRESS }} --username ${{ secrets.GIT_LOGIN }} --password ${{ secrets.GIT_TOKEN }}  –upsert






          
