name: create yandex cluster

on:
  workflow_dispatch
#  push:
    # при создании pull request на main
#    branches: [ main ]

jobs:
  create_cluster:
    runs-on: ubuntu-latest
    env:
      ya_cluster_name: ${{ vars.YA_CLUSTER_NAME }}
      ya_network-name: default
      ya_zone: ru-central1-a
      ya_subnet: default-ru-central1-a
      ya_account: ${{ secrets.YA_ACCOUNT }}
      ya_cloud_id: ${{ vars.YA_CLUSTER_ID }}
      ya_folder_id: ${{ vars.YA_FOLDER_ID }}
      ya_kms_key: keyencrypt
      
   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name:  install yandex cli
        uses: nightstory/setup-yc@v1
        with:
          enable-cache: true

      - run: 'echo "$YA_KEY" > key.json'
        shell: bash
        env:
          YA_KEY: ${{ secrets.YC_SA }}
    
      - name: set yandex env
        run: |
          yc config set cloud-id ${{ env.ya_cloud_id }}
          yc config set folder-id ${{ env.ya_folder_id }}
          yc config set service-account-key key.json
   
      - name: Create cluster
        run: |
          yc managed-kubernetes cluster create \
          --name ${{ env.ya_cluster_name }} \
          --network-name ${{ env.ya_network-name }} \
          --zone ${{ env.ya_zone }} \
          --subnet-name ${{ env.ya_subnet }} \
          --public-ip \
          --release-channel regular \
          --version 1.26 \
          --cluster-ipv4-range 172.16.16.0/22 \
          --service-ipv4-range 172.16.20.0/22 \
          --node-ipv4-mask-size 26 \
          --service-account-name ${{ env.ya_account }} \
          --node-service-account-name ${{ env.ya_account }} \
          --kms-key-name ${{ env.ya_kms_key }}
 
      - name: Create nodes
        run: |
          yc managed-kubernetes node-group create \
          --cluster-name ${{ env.ya_cluster_name }} \
          --cores 4 \
          --core-fraction 20 \
          --disk-size 64 \
          --disk-type network-hdd \
          --fixed-size 2 \
          --memory 4 \
          --name testgroup \
          --platform-id standard-v3 \
          --container-runtime containerd \
          --preemptible \
          --network-interface subnets=${{ env.ya_subnet }} \
          --metadata ssh-keys="${{ secrets.YC_SSH_KEY }}" \
          --public-ip
          
 





          
