name: ci

on:
  push:
    # при создании pull request на main
    branches: [ main ]

jobs:
  create_cluster:
    runs-on: ubuntu-latest
    env:
      ya_cluster_name: testcluster
      ya_network-name: default
      ya_zone: ru-central1-a
      ya_subnet: default-ru-central1-a
      ya_account: svckursovik
      ya_cloud_id: b1gi91nvj5m7ajci95v9
      ya_folder_id: b1g38fjsltr2a35lkcg3
   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Yandex Cloud login
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA }}

#      - name: install CLI
#        run: |
 #         curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -a

      - name:  test ya
        uses: nightstory/setup-yc@v1
        with:
          enable-cache: true

#      - name: install kubectl
#        run: |
#          sudo apt-get update && sudo apt-get install -y apt-transport-https
#          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
#          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
 #         sudo apt-get update
#          sudo apt-get install -y kubectl
#      - name:  test ya
#        uses: nikita-volkov/yc-cli.github-action@v1.0.0
#        with: 
#          key: ${{ secrets.YC_SA }}
#          args: config set cloud-id ${{ env.ya_cloud_id }}

      - name: IAM Token
        id: issue-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA }}

      - run: 'echo "$SSH_KEY" > key.json'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.YC_SA }}
    
#      - name: Create key
#        run: |
#          echo ${{ secrets.YC_SA }} > key.json

      - name: set yandex env
        run: |
          yc config set cloud-id ${{ env.ya_cloud_id }}
          yc config set folder-id ${{ env.ya_folder_id }}
          yc config set service-account-key key.json

      - name: Create cluster
#        uses: nikita-volkov/yc-cli.github-action@v1.0.0
#        with:
# #         key: ${{ secrets.YC_SA }}  
        run: |
          yc managed-kubernetes cluster create \
          --name ${{ env.ya_cluster_name }} \
          --network-name ${{ env.ya_network-name }} \
          --zone ${{ env.ya_zone }} \
          --subnet-name ${{ env.ya_subnet }} \
          --public-ip \
          --release-channel regular \
          --version 1.26 \
          --cluster-ipv4-range 172.16.1.0/16 \
          --service-ipv4-range 172.17.1.0/16 \
          --service-account-name ${{ env.ya_account }} \
          --node-service-account-name ${{ env.ya_account }} 



#      - name: Create cluster
#        uses: nikita-volkov/yc-cli.github-action@v1.0.0
#        with:
# #         key: ${{ secrets.YC_SA }}  
#          args: |
#            managed-kubernetes cluster create \
#              --name ${{ env.ya_cluster_name }} \
#              --network-name ${{ env.ya_network-name }} \
#              --zone ${{ env.ya_zone }} \
#              --subnet-name ${{ env.ya_subnet }} \
#              --public-ip \
#              --release-channel regular \
#              --version 1.25 \
#              --cluster-ipv4-range 172.16.1.0/16 \
#              --service-ipv4-range 1172.17.1.0/16 \
#              --service-account-name ${{ env.ya_account }} \
#              --node-service-account-name ${{ env.ya_account }} \



          
